version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-dnc-boilerplate-stack-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2ezwejqwwvcm"
s3_prefix = "sam-dnc-boilerplate-stack-dev"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ServiceName=\"sam-items-api\" ApiStageName=\"dev\""

